//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace courseWork02
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MoneyPred : DbContext
    {
        public MoneyPred()
            : base("name=MoneyPred")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Appoinment> Appoinments { get; set; }
        public virtual DbSet<Expense> Expenses { get; set; }
        public virtual DbSet<ExpenseCategory> ExpenseCategories { get; set; }
        public virtual DbSet<Income> Incomes { get; set; }
        public virtual DbSet<User> Users { get; set; }
    
        public virtual ObjectResult<Get_All_Result> Get_All()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_All_Result>("Get_All");
        }
    
        public virtual ObjectResult<Get_Allii_Result> Get_Allii()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Allii_Result>("Get_Allii");
        }
    }
}
